[package]
edition = "2021"
name = "abi"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11"
prost-types = "0.11.2"
tonic = "0.8.3"

[build-dependencies]
tonic-build = "0.8.3"
